In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib

%matplotlib inline
matplotlib.rcParams.update({'font.size': 16})
np.set_printoptions(precision=2,suppress=True)

# Simple SIR Model

$X_k = X_0 \cdot A^k$

In [21]:
# size of the population
num_pop = 1000.

# number of infected individuals
num_infect = 2.

# Define the SIR matrix (entries are probabilities)
sir_mat = np.array([[0.8, 0.2, 0., 0.],
                    [0., 0.5, 0.4, 0.1],
                    [0., 0., 1., 0.],
                    [0., 0., 0., 1.]])

# Define the initial state vector (entries are numbers of people)
x = np.array([num_pop-num_infect,num_infect,0.,0.], ndmin=2)

print('Initial state vector X_0:\n{}'.format(x))
print('\nSIR Update Model:\n{}'.format(sir_mat))

Initial state vector X_0:
[[998.   2.   0.   0.]]

SIR Update Model:
[[0.8 0.2 0.  0. ]
 [0.  0.5 0.4 0.1]
 [0.  0.  1.  0. ]
 [0.  0.  0.  1. ]]


In [22]:
n_steps = 20
for s in range(n_steps):
  x = np.dot(x, sir_mat) # or matmul
  
print(x)


[[ 11.51   7.67 784.66 196.16]]


# SIR Model - v2

A more accurate (but still pretty simple) SIR model follows:

* $S_{n+1}=S_n(1-\frac{\beta}{N}I_n)$

* $I_{n+1}=I_n(1+\frac{\beta}{N}S_n-\gamma-\alpha)$

* $R_{n+1}=R_n+\gamma I_n$

* $D_{n+1}=D_n+\alpha I_n$

where $\beta$ represents the probability of an S person becoming infected upon contact with an I, $\gamma$ is the probability of an I person recovering, and $\alpha$ is the probability of an I person dying.  Note that $1/\gamma$ is the average length of the infection period.

In [0]:
# size of the population
num_pop = 1000.

# number of infected individuals
num_infect = 5.

beta = 0.2
gamma = 0.15
alpha = 0.01

S = num_pop-num_infect
I = num_infect
R = 0
D = 0

In [64]:
sir_df = pd.DataFrame(columns=['S','I','R','D'])
sir_df.loc[0] = ([S, I, R, D])

n_steps = 200
for s in range(n_steps):
    S *= (1-beta/num_pop*sir_df.loc[s]["I"])
    I *= (1 + beta/num_pop*sir_df.loc[s]["S"] - gamma - alpha)
    R += gamma*sir_df.loc[s]["D"]
    D += alpha*sir_df.loc[s]["I"]
    sir_df.loc[s+1] = ([S, I, R, D])
sir_df

S          I           R          D
0    995.000000   5.000000    0.000000   0.000000
1    994.005000   5.195000    0.000000   0.050000
2    992.972229   5.396571    0.007500   0.101950
3    991.900500   5.604849    0.022793   0.155916
4    990.788609   5.819964    0.046180   0.211964
5    989.635339   6.042040    0.077974   0.270164
6    988.439455   6.271197    0.118499   0.330584
7    987.199716   6.507545    0.168087   0.393296
8    985.914866   6.751187    0.227081   0.458372
9    984.583647   7.002216    0.295837   0.525884
10   983.204793   7.260715    0.374719   0.595906
11   981.777039   7.526755    0.464105   0.668513
12   980.299120   7.800393    0.564382   0.743780
13   978.769777   8.081674    0.675949   0.821784
14   977.187757   8.370626    0.799217   0.902601
15   975.551822   8.667260    0.934607   0.986307
16   973.860750   8.971571    1.082553   1.072980
17   972.113338   9.283532    1.243500   1.162696
18   970.308409   9.603096    1.417904   1.255531
19   968.444816   9.930193    1.606234   1.351562
20   966.521447  10.264731    1.808968   1.450864
21   964.537231  10.606591    2.026598   1.553511
22   962.491140  10.955627    2.259625   1.659577
23   960.382202  11.311665    2.508561   1.769133
24   958.209497  11.674503    2.773931   1.882250
25   955.972173  12.043906    3.056269   1.998995
26   953.669445  12.419609    3.356118   2.119434
27   951.300605  12.801312    3.674033   2.243630
28   948.865026  13.188681    4.010578   2.371643
29   946.362170  13.581348    4.366324   2.503530
..          ...        ...         ...        ...
171  618.687829   1.895005  340.915005  23.713573
172  618.453345   1.826288  344.472041  23.732523
173  618.227450   1.759976  348.031920  23.750786
174  618.009837   1.695993  351.594537  23.768386
175  617.800209   1.634263  355.159795  23.785346
176  617.598280   1.574710  358.727597  23.801688
177  617.403772   1.517264  362.297850  23.817435
178  617.216419   1.461855  365.870466  23.832608
179  617.035963   1.408414  369.445357  23.847226
180  616.862154   1.356876  373.022441  23.861311
181  616.694753   1.307177  376.601637  23.874879
182  616.533527   1.259255  380.182869  23.887951
183  616.378253   1.213049  383.766062  23.900544
184  616.228714   1.168500  387.351143  23.912674
185  616.084701   1.125553  390.938045  23.924359
186  615.946014   1.084152  394.526698  23.935615
187  615.812458   1.044243  398.117041  23.946456
188  615.683846   1.005776  401.709009  23.956899
189  615.559998   0.968700  405.302544  23.966956
190  615.440740   0.932966  408.897587  23.976643
191  615.325903   0.898529  412.494084  23.985973
192  615.215325   0.865342  416.091980  23.994958
193  615.108851   0.833361  419.691224  24.003612
194  615.006329   0.802545  423.291765  24.011945
195  614.907615   0.772852  426.893557  24.019971
196  614.812569   0.744242  430.496553  24.027699
197  614.721055   0.716677  434.100708  24.035142
198  614.632944   0.690120  437.705979  24.042309
199  614.548109   0.664535  441.312325  24.049210
200  614.466432   0.639887  444.919707  24.055855

[201 rows x 4 columns]